version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
      - "8501:8501"
    volumes:
      - .:/app
      - ./frontend:/app/frontend
      - /app/.pixi  # Exclude .pixi from being overwritten
    entrypoint: ["/bin/sh", "-c", "mkdir -p /app/logs && supervisord -c /etc/supervisor/conf.d/supervisord.conf"]
