[project]
name = "bioethics-rag"
version = "0.1.0"
description = "Bioethics Chatbot"
authors = ["Landung 'Don' Setiawan <landungs@uw.edu>"]
channels = ["conda-forge", "pytorch"]
platforms = ["osx-arm64"]

[environments]
frontend = ["frontend"]
backend = ["backend"]

[feature.frontend.tasks.streamlit]
cmd = "streamlit run frontend/app.py --server.port 8501 --server.address 0.0.0.0"

[feature.backend.tasks.server]
cmd = "uvicorn app.main:app --host 0.0.0.0 --port 8000"

[dependencies]
python = "3.11.*"
pixi-kernel = ">=0.4.0,<0.5"

[feature.frontend.dependencies]
numpy = ">=1.21.0,<2"
streamlit = ">=1.44.1"
tenacity = ">=8.1.0,<9.0.0"

[feature.frontend.pypi-dependencies]
langchain = "==0.2.3"
langchain-community = "==0.2.4"
pymupdf = ">=1.24.10, <1.25"
python-docx = "*"

[feature.backend.dependencies]
numpy = ">=1.21.0,<2"
pytest = ">=8.3.5,<9"
fastapi = ">=0.115.11,<0.116"
uvicorn = "==0.34.2"
packaging = "==24.0"

[feature.backend.pypi-dependencies]
langchain = "==0.2.3"
langchain-core = "==0.2.28"
langchain-community = "==0.2.4"
langchain-qdrant = "==0.1.0"
langchain-huggingface = "==0.0.3"
qdrant-client = ">=1.14.2"
sentence-transformers = ">=4.1.0"
pymupdf = ">=1.25.5"
transformers = "==4.51.3"
accelerate = ">=0.26.0"
bitsandbytes = ">=0.42.0, <0.46"
