[supervisord]
nodaemon=true

[program:fastapi]
command=/app/.pixi/envs/default/bin/uvicorn app.main:app --host 0.0.0.0 --port 8000
directory=/app
autostart=true
autorestart=true
stderr_logfile=/var/log/fastapi.err.log
stdout_logfile=/var/log/fastapi.out.log

[program:streamlit]
command=/bin/sh -c "sleep 5 && /app/.pixi/envs/frontend/bin/streamlit run /app/frontend/app.py --server.port 8501 --server.address 0.0.0.0"
directory=/app/frontend
autostart=true
autorestart=true
stderr_logfile=/var/log/streamlit.err.log
stdout_logfile=/var/log/streamlit.out.log
environment=PATH="/app/.pixi/envs/frontend/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
